environment:
  matrix:
  - NODE_VERSION: "12"
  - NODE_VERSION: "14"

platform:
  - x86
  - x64

matrix:
  fast_finish: true

install:
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:NODE_VERSION) $env:Platform
  - node --version
  - npm --version
  - npm install
  - npm install --global elm
  - npm run make

test_script:
  - npm test

build: off
