sudo: false

language: node_js
node_js:
  - "node"
  - "4"

cache:
  directories:
    - sysconfcpus
    - node_modules
    - elm-stuff/build-artifacts
    - tests/data/simple/elm-stuff/build-artifacts
    - tests/data/simple/tests/elm-stuff/build-artifacts

os:
  - linux
  - osx

env: ELM_VERSION=0.19.0
env: ELM_TEST_VERSION=latest

install:
  - node --version
  - npm --version
  - npm install -g elm@$ELM_VERSION elm-test@$ELM_TEST_VERSION
  - npm install
  - npm run make

script:
  - npm test
