sudo: false

language: node_js
node_js:
  - "node"
  - "4"

cache:
  directories:
    - sysconfcpus
    - node_modules
    - elm-stuff/build-artifacts
    - tests/data/simple/elm-stuff/build-artifacts
    - tests/data/simple/tests/elm-stuff/build-artifacts

os:
  - linux
  - osx

env: ELM_VERSION=0.18.0
env: ELM_TEST_VERSION=latest

before_install:
  - | # epic build time improvement - see https://github.com/elm-lang/elm-compiler/issues/1473#issuecomment-245704142
    if [ ! -d sysconfcpus/bin ];
    then
      git clone https://github.com/obmarg/libsysconfcpus.git;
      cd libsysconfcpus;
      ./configure --prefix=$TRAVIS_BUILD_DIR/sysconfcpus;
      make && make install;
      cd ..;
    fi
  
install:
  - node --version
  - npm --version
  - npm install -g elm@$ELM_VERSION elm-test@$ELM_TEST_VERSION
  - mv $(npm config get prefix)/bin/elm-make $(npm config get prefix)/bin/elm-make-old
  - echo -e "#\!/bin/bash\\n\\necho \"Running elm-make with sysconfcpus -n 2\"\\n\\n$TRAVIS_BUILD_DIR/sysconfcpus/bin/sysconfcpus -n 2 elm-make-old \"\$@\"" > $(npm config get prefix)/bin/elm-make
  - chmod +x $(npm config get prefix)/bin/elm-make
  - npm install
  - npm run make

script:
  - npm test
