environment:
  ELM_VERSION: "0.18.0"
  ELM_TEST_VERSION: "latest"
  matrix:
  - NODE_VERSION: "8"
  - NODE_VERSION: "4"

platform:
  - x86
  - x64

matrix:
  fast_finish: true

install:
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:NODE_VERSION) $env:Platform
  - node --version
  - npm --version
  - npm install -g elm@%ELM_VERSION% elm-test@%ELMTEST_VERSION%
  - npm install

test_script:
  - npm test

build: off
