environment:
  ELM_VERSION: "0.19.0"
  ELM_TEST_VERSION: "latest"
  APPVEYOR_RDP_PASSWORD:
    secure: QRKyprxCq+yWBbuOlYFGIPl8n2b05U3q7fAupLYdUKA=
  matrix:
  - NODE_VERSION: "8"
  - NODE_VERSION: "4"

init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))


platform:
  - x86
  - x64


matrix:
  fast_finish: true


install:
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:NODE_VERSION) $env:Platform
  - node --version
  - npm --version
  - npm install -g elm@%ELM_VERSION% elm-test@%ELM_TEST_VERSION%
  - elm --version && elm-test --version
  - npm ci
  - ps: dir
  - node foo.js


test_script:
  - npm test


build: off
